platform :ios, '14.0'

target 'CurrencyConvertApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CurrencyConvertApp
pod 'SwiftyUIX', :git => 'https://github.com/Mokshsuthar/SwiftyUIX'

end
